resource_group_name = "my-resource-group"
location            = "East US"
vm_name             = "my-vm"
vm_size             = "Standard_DS2_v2"
admin_username      = "adminuser"
admin_password      = "P@ssw0rd123"
